dependencies:
- pip:
  - asttokens==2.4.1
  - colorama==0.4.6
  - comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1710320294760/work
  - contourpy==1.2.1
  - cycler==0.12.1
  - debugpy==1.8.1
  - decorator==5.1.1
  - exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1720869315914/work
  - executing==2.0.1
  - filelock==3.15.4
  - fonttools==4.53.1
  - fsspec==2024.6.1
  - imageio==2.34.2
  - importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1721856510709/work
  - ipykernel @ file:///D:/bld/ipykernel_1719845595208/work
  - ipython @ file:///D:/bld/ipython_1719582682925/work
  - ipywidgets==8.1.3
  - jedi==0.19.1
  - Jinja2==3.1.4
  - joblib==1.4.2
  - jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1716472197302/work
  - jupyter_core @ file:///D:/bld/jupyter_core_1710257295326/work
  - jupyterlab_widgets==3.0.11
  - kiwisolver==1.4.5
  - lazy_loader==0.4
  - MarkupSafe==2.1.5
  - matplotlib==3.9.0
  - matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1713250518406/work
  - mpmath==1.3.0
  - nest-asyncio==1.6.0
  - networkx==3.3
  - nibabel==5.2.1
  - numpy==2.0.1
  - opencv-python==4.10.0.84
  - packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1718189413536/work
  - parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1712320355065/work
  - pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
  - pillow==10.4.0
  - platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1715777629804/work
  - prompt-toolkit==3.0.43
  - psutil==5.9.8
  - pure-eval==0.2.2
  - Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1714846767233/work
  - pyparsing==3.1.2
  - python-dateutil==2.9.0.post0
  - pywin32==306
  - PyYAML==6.0.1
  - pyzmq @ file:///D:/bld/pyzmq_1715024498246/work
  - scikit-image==0.24.0
  - scikit-learn==1.5.1
  - scipy==1.14.0
  - setuptools==72.1.0
  - six==1.16.0
  - stack-data==0.6.3
  - sympy==1.13.1
  - threadpoolctl==3.5.0
  - tifffile==2024.7.24
  - torch==2.4.0
  - torchcubicspline @ git+https://github.com/patrick-kidger/torchcubicspline.git@d16c6bf5b63d03dbf2977c70e19a320653b5e4a8
  - tornado==6.4
  - traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1713535121073/work
  - typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1717802530399/work
  - wcwidth==0.2.13
  - wheel==0.44.0
  - widgetsnbextension==4.0.11
  - zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1718013267051/work
